version: "3"
services:
    app:
        image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:latest
        ports:
            - "8080:80"
        environment:
            - REACT_APP_LOGIN=${REACT_APP_LOGIN}
            - REACT_APP_PASSWORD=${REACT_APP_PASSWORD}
            - REACT_APP_LOGIN_API=${REACT_APP_LOGIN_API}
            - REACT_APP_ACCESS_TOKEN=${REACT_APP_ACCESS_TOKEN}
            - REACT_APP_CARDS_API=${REACT_APP_CARDS_API}
            - REACT_APP_USER_API=${REACT_APP_USER_API}
