version: "3"
services:
    app:
        build:
            context: .
            args:
                REACT_APP_LOGIN: ${REACT_APP_LOGIN}
                REACT_APP_PASSWORD: ${REACT_APP_PASSWORD}
                REACT_APP_LOGIN_API: ${REACT_APP_LOGIN_API}
                REACT_APP_ACCESS_TOKEN: ${REACT_APP_ACCESS_TOKEN}
                REACT_APP_CARDS_API: ${REACT_APP_CARDS_API}
                REACT_APP_GET_USER_API: ${REACT_APP_GET_USER_API}
                REACT_APP_SET_USER_API: ${REACT_APP_SET_USER_API}
        ports:
            - "8080:80"
