export enum Actions {
	AUTH_SUCCESS = "AUTH_SUCCESS",
	INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
	AUTH_FAILURE = "AUTH_FAILURE",
	LOGOUT = "LOGOUT",
	SET_USER = "SET_USER",
	CLOSE_ALERT = "CLOSE_ALERT",
}
