export enum Actions {
	AUTH_SUCCESS = "AUTH_SUCCESS",
	LOGOUT = "LOGOUT",
	GET_USER = "GET_USER",
	SET_USER = "SET_USER",
	OPEN_ALERT = "OPEN_ALERT",
	CLOSE_ALERT = "CLOSE_ALERT",
	GET_CARDS = "GET_CARDS",
}
