export enum Actions {
	AUTH_SUCCESS = "AUTH_SUCCESS",
	LOGOUT = "LOGOUT",
	UPDATE_USER = "UPDATE_USER",
	SET_USER = "SET_USER",
	DELETE_USER = "DELETE_USER",
	OPEN_ALERT = "OPEN_ALERT",
	CLOSE_ALERT = "CLOSE_ALERT",
	GET_CARDS = "GET_CARDS",
}
