name: CI/CD for SPA-ASTRAL

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:latest

            - name: Deploy to Portainer
              env:
                  PORTAINER_API_KEY: ${{ secrets.PORTAINER_API_KEY }}
                  PORTAINER_HOST: ${{ secrets.PORTAINER_HOST }}
              run: |
                  curl -X POST "${PORTAINER_HOST}/api/stacks" \
                       -H "Authorization: Bearer ${PORTAINER_API_KEY}" \
                       -H "Content-Type: application/json" \
                       --data-binary @stack-definition.json
